// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATtnhpjxaRzmQfWcR5MdB53WJXQenSWy4',
    appId: '1:136156591893:web:db8d1ab449f38dfe615b1c',
    messagingSenderId: '136156591893',
    projectId: 'togetherapart-cd369',
    authDomain: 'togetherapart-cd369.firebaseapp.com',
    storageBucket: 'togetherapart-cd369.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8y8xXJ5MoSeE9masOI0sErY3BFSnwg4U',
    appId: '1:136156591893:android:a05c5f351d2d17ec615b1c',
    messagingSenderId: '136156591893',
    projectId: 'togetherapart-cd369',
    storageBucket: 'togetherapart-cd369.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8cqDUGcczkVU7ljsNtlVqtMYQiSZfca4',
    appId: '1:136156591893:ios:42dfb0c7ccdcad13615b1c',
    messagingSenderId: '136156591893',
    projectId: 'togetherapart-cd369',
    storageBucket: 'togetherapart-cd369.appspot.com',
    iosClientId: '136156591893-f95l440fnc3ogk4p186k79hordiuh266.apps.googleusercontent.com',
    iosBundleId: 'com.example.togetherapart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8cqDUGcczkVU7ljsNtlVqtMYQiSZfca4',
    appId: '1:136156591893:ios:42dfb0c7ccdcad13615b1c',
    messagingSenderId: '136156591893',
    projectId: 'togetherapart-cd369',
    storageBucket: 'togetherapart-cd369.appspot.com',
    iosClientId: '136156591893-f95l440fnc3ogk4p186k79hordiuh266.apps.googleusercontent.com',
    iosBundleId: 'com.example.togetherapart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATtnhpjxaRzmQfWcR5MdB53WJXQenSWy4',
    appId: '1:136156591893:web:0cceebc45784f739615b1c',
    messagingSenderId: '136156591893',
    projectId: 'togetherapart-cd369',
    authDomain: 'togetherapart-cd369.firebaseapp.com',
    storageBucket: 'togetherapart-cd369.appspot.com',
  );
}
